name: dockerphp-test
services:
  #php74s6:
  #  build:
  #    context: "./php74"
  #    dockerfile: Dockerfile
  #  container_name: php74s6_cntr
  #  image: php74s6_img
  #  platform: "linux/amd64"
  #  ports: 
  #    - 3023:8080
  #  networks:
  #    - localnetwork
  php83s6:
    build:
      context: "./php83"
      dockerfile: Dockerfile
    container_name: php82s6_cntr
    image: php83s6_img
    platform: "linux/amd64"
    ports: 
      - 3022:8080
    networks:
      - localnetwork
networks:
  localnetwork:
    driver: bridge